server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: library
          uri: http://localhost:8080
          predicates:
            - Path=/library/**